### PR TITLE
Improve threadsafety

### PR DESCRIPTION
**Pull request by igmar**
- Implement ReadWrite lock in TemplateClass
- Remove public variables from TemplateClass

### CODE REVIEW

**Comment by igmar** [comment]
This pull improves threadsafety. I don't consider this to be a proper fix, for that we need : 

- Remove all public variables from classes

and

1) Make classes immutable
or
2) Implement proper locking

The biggest problem is the huge amount of shared state : That makes proper locking a real tough job. It's mostly needed for enhancing and reloading in dev mode. I suggest we make classes immutable, so a change to a template source means new TemplateClass + enhancement.

This will come with a penalty at runtime, bit since it's dev mode, I'm pretty OK with it.
This merge is mainly focussed at TemplateClass, I'll also dive into the rest.

**Comment by greenlaw110** [comment]
@igmar when I run `mvn clean test` the process is hanging there and `jstack` gives me these stack info:

```
"main" prio=10 tid=0x00007f435000a800 nid=0x4d8b waiting on condition [0x00007f4356a79000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007adb54330> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
        at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:945)
        at org.rythmengine.internal.compiler.TemplateClass.compile(TemplateClass.java:787)
        at org.rythmengine.internal.compiler.TemplateClassLoader.loadTemplateClass(TemplateClassLoader.java:309)
        at org.rythmengine.internal.compiler.TemplateClassLoader.loadClass(TemplateClassLoader.java:254)
        - locked <0x00000007ad86e558> (a org.rythmengine.internal.compiler.TemplateClassLoader)
        at org.rythmengine.internal.compiler.TemplateClass.loadJavaClass(TemplateClass.java:468)
        at org.rythmengine.internal.compiler.TemplateClass.templateInstance_(TemplateClass.java:483)
        at org.rythmengine.internal.compiler.TemplateClass.asTemplate(TemplateClass.java:515)
        at org.rythmengine.internal.compiler.TemplateClass.asTemplate(TemplateClass.java:524)
        at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:903)
        at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:924)
        at org.rythmengine.RythmEngine.render(RythmEngine.java:998)
        at org.rythmengine.Rythm.render(Rythm.java:305)
        at org.rythmengine.TestBase.r(TestBase.java:51)
```

**Comment by igmar** [comment]
which JVM is this ?

**Comment by igmar** [comment]
I can reproduce now indeed. Checking, will update the old branch I did with a fix.

**Comment by igmar** [comment]
I already see it :  TemplateClass calls itself, which after first getting a read lock, tries to acquire a write lock. I'll need to revise this.

**Comment by igmar** [comment]
I'm trying to upgrade a read lock to a writelock, and that's not allowed it seems. Will need to refactor this.

**Pull request merged**
